### ISSUE TITLE
Refine Custom Algolia Hit Cards

### ISSUE THREAD

**Issue by zachdt** [leaseOTB/billboard#3]
Right now, the only thing on our search results in a small picture of the building, the street address, and the ZIP code.  Not sure what other data we can put on the cards, but I would like these hits to look better.  Maybe use a table or list or something.... totally up in the air.  

Here are the current attributes of each hit.

STREET_ADDRESS

BBL

ZIP

objectID

_id

INC_2019

INC_2020

INCREASE

**Comment by Josh1794** [comment]
will work on this this weekend
